# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d382042262f9bad040684d2aa9fbbefda591d49273aa4b195e96b8204a22c25661f44f8e048c4108a49d7089a768427b728d01d4f512c5bd2514652133682e8

test:
  secret_key_base: 3335d7e164296641a234051058242b5d9d9dd4f88696389d20e6636057f2661266c74e9e62e6463d1bb358a35e32bac656d72b9982dc1c8281835c1495049d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
